pipeline:
  identifier: Build_Prateekbhaisare_Game_1766737235126
  name: Build Game
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github
        repoName: Prateekbhaisare/Game
  stages:
    - stage:
        identifier: build
        name: build
        type: CI
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
            selectors:
              - docker-delegate
              - linux-amd64
          runtime:
            type: Docker
            spec:
              harnessImageConnectorRef: account.harnessImage
          execution:
            steps:
              - step:
                  identifier: echo
                  name: echo
                  type: Run
                  spec:
                    command: echo "hello world"
